/*
 * Copyright 2019-2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */
/*
 * Generated from mdc2_prov.c.in for https://github.com/kiyolee/openssl.git.
 */


/*
 * MDC2 low level APIs are deprecated for public use, but still ok for
 * internal use.
 */
#include "internal/deprecated.h"

#include <string.h>
#include <openssl/crypto.h>
#include <openssl/params.h>
#include <openssl/mdc2.h>
#include <openssl/core_names.h>
#include <openssl/err.h>
#include <openssl/proverr.h>
#include <internal/common.h>
#include "prov/digestcommon.h"
#include "prov/implementations.h"

static OSSL_FUNC_digest_set_ctx_params_fn mdc2_set_ctx_params;
static OSSL_FUNC_digest_settable_ctx_params_fn mdc2_settable_ctx_params;

/* Machine generated by util/perl/OpenSSL/paramnames.pm */
#ifndef mdc2_set_ctx_params_list
static const OSSL_PARAM mdc2_set_ctx_params_list[] = {
    OSSL_PARAM_uint(OSSL_DIGEST_PARAM_PAD_TYPE, NULL),
    OSSL_PARAM_END
};
#endif

#ifndef mdc2_set_ctx_params_st
struct mdc2_set_ctx_params_st {
    OSSL_PARAM *pad;
};
#endif

#ifndef mdc2_set_ctx_params_decoder
static int mdc2_set_ctx_params_decoder
    (const OSSL_PARAM *p, struct mdc2_set_ctx_params_st *r)
{
    const char *s;

    memset(r, 0, sizeof(*r));
    if (p != NULL)
        for (; (s = p->key) != NULL; p++)
            if (ossl_likely(strcmp("pad-type", s + 0) == 0)) {
                /* OSSL_DIGEST_PARAM_PAD_TYPE */
                if (ossl_unlikely(r->pad != NULL)) {
                    ERR_raise_data(ERR_LIB_PROV, PROV_R_REPEATED_PARAMETER,
                                   "param %s is repeated", s);
                    return 0;
                }
                r->pad = (OSSL_PARAM *)p;
            }
    return 1;
}
#endif
/* End of machine generated */

static const OSSL_PARAM *mdc2_settable_ctx_params(ossl_unused void *ctx,
                                                  ossl_unused void *provctx)
{
    return mdc2_set_ctx_params_list;
}

static int mdc2_set_ctx_params(void *vctx, const OSSL_PARAM params[])
{
    struct mdc2_set_ctx_params_st p;
    MDC2_CTX *ctx = (MDC2_CTX *)vctx;

    if (ctx == NULL || !mdc2_set_ctx_params_decoder(params, &p))
        return 0;

    if (p.pad != NULL && !OSSL_PARAM_get_uint(p.pad, &ctx->pad_type)) {
        ERR_raise(ERR_LIB_PROV, PROV_R_FAILED_TO_GET_PARAMETER);
        return 0;
    }
    return 1;
}

/* ossl_mdc2_functions */
IMPLEMENT_digest_functions_with_settable_ctx(
    mdc2, MDC2_CTX, MDC2_BLOCK, MDC2_DIGEST_LENGTH, 0,
    MDC2_Init, MDC2_Update, MDC2_Final,
    mdc2_settable_ctx_params, mdc2_set_ctx_params)
