/*
 * Copyright 2016-2026 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */
/*
 * Generated by configdata.pm for https://github.com/kiyolee/openssl.git.
 */

#ifndef APPS_CONFIGURATION_H
#define APPS_CONFIGURATION_H

/* clang-format off */
static const char * const openssl_disabled_protocols[] = {
	"",
	"KTLS",
	"SCTP",
	"TLS-DEPRECATED-EC",
};

static const char * const openssl_disabled_algorithms[] = {
	"",
	"BROTLI",
	"LMS",
	"MD2",
	"RC5",
	"ZSTD",
};

static const char * const openssl_disabled_features[] = {
	"",
	"ACVP-TESTS",
	"ALLOCFAIL-TESTS",
	"ASAN",
	"BROTLI-DYNAMIC",
	"CRYPTO-MDEBUG",
	"CT-VALIDATION",
	"DEMOS",
	"EC_EXPLICIT_CURVES",
	"EC_NISTP_64_GCC_128",
	"EGD",
	"EXTERNAL-TESTS",
	"FIPS-JITTER",
	"FIPS-POST",
	"FIPS-SECURITYCHECKS",
	"FUZZ-AFL",
	"FUZZ-LIBFUZZER",
	"H3DEMO",
	"HQINTEROP",
	"JITTER",
	"MSAN",
	"PIE",
	"SSLKEYLOG",
	"STATIC-VCRUNTIME",
	"TFO",
	"TRACE",
	"UBSAN",
	"UNIT-TEST",
#if defined(OPENSSL_STATIC_LIB) || defined(_M_ARM) || defined(_M_ARM64)
	"UPLINK",
#endif
	"WEAK-SSL-CIPHERS",
	"ZLIB-DYNAMIC",
	"ZSTD-DYNAMIC",
};

/* clang-format on */

#endif
